/*
 * This file is generated by jOOQ.
*/
package com.nabenik.model;


import com.nabenik.model.tables.Movie;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.movie</code>.
     */
    public static final Movie MOVIE = com.nabenik.model.tables.Movie.MOVIE;
}
