/*
 * This file is generated by jOOQ.
*/
package com.nabenik.model.tables.records;


import com.nabenik.model.tables.Movie;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovieRecord extends UpdatableRecordImpl<MovieRecord> implements Record14<Long, String, Integer, Integer, String, String, String, String, String, String, Long, Integer, Double, Long> {

    private static final long serialVersionUID = 1456749263;

    /**
     * Setter for <code>public.movie.movie_id</code>.
     */
    public void setMovieId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.movie.movie_id</code>.
     */
    public Long getMovieId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.movie.director_name</code>.
     */
    public void setDirectorName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.movie.director_name</code>.
     */
    public String getDirectorName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.movie.duration</code>.
     */
    public void setDuration(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.movie.duration</code>.
     */
    public Integer getDuration() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.movie.gross</code>.
     */
    public void setGross(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.movie.gross</code>.
     */
    public Integer getGross() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.movie.genres</code>.
     */
    public void setGenres(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.movie.genres</code>.
     */
    public String getGenres() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.movie.movie_title</code>.
     */
    public void setMovieTitle(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.movie.movie_title</code>.
     */
    public String getMovieTitle() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.movie.plot_keywords</code>.
     */
    public void setPlotKeywords(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.movie.plot_keywords</code>.
     */
    public String getPlotKeywords() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.movie.movie_imdb_link</code>.
     */
    public void setMovieImdbLink(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.movie.movie_imdb_link</code>.
     */
    public String getMovieImdbLink() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.movie.country</code>.
     */
    public void setCountry(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.movie.country</code>.
     */
    public String getCountry() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.movie.content_rating</code>.
     */
    public void setContentRating(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.movie.content_rating</code>.
     */
    public String getContentRating() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.movie.budget</code>.
     */
    public void setBudget(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.movie.budget</code>.
     */
    public Long getBudget() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.movie.title_year</code>.
     */
    public void setTitleYear(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.movie.title_year</code>.
     */
    public Integer getTitleYear() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.movie.imdb_score</code>.
     */
    public void setImdbScore(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.movie.imdb_score</code>.
     */
    public Double getImdbScore() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>public.movie.movie_facebook_likes</code>.
     */
    public void setMovieFacebookLikes(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.movie.movie_facebook_likes</code>.
     */
    public Long getMovieFacebookLikes() {
        return (Long) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, String, Integer, Integer, String, String, String, String, String, String, Long, Integer, Double, Long> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, String, Integer, Integer, String, String, String, String, String, String, Long, Integer, Double, Long> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Movie.MOVIE.MOVIE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Movie.MOVIE.DIRECTOR_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Movie.MOVIE.DURATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Movie.MOVIE.GROSS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Movie.MOVIE.GENRES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Movie.MOVIE.MOVIE_TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Movie.MOVIE.PLOT_KEYWORDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Movie.MOVIE.MOVIE_IMDB_LINK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Movie.MOVIE.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Movie.MOVIE.CONTENT_RATING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return Movie.MOVIE.BUDGET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return Movie.MOVIE.TITLE_YEAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field13() {
        return Movie.MOVIE.IMDB_SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field14() {
        return Movie.MOVIE.MOVIE_FACEBOOK_LIKES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getMovieId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDirectorName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getGross();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getGenres();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getMovieTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPlotKeywords();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getMovieImdbLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getContentRating();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getBudget();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getTitleYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value13() {
        return getImdbScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value14() {
        return getMovieFacebookLikes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value1(Long value) {
        setMovieId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value2(String value) {
        setDirectorName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value3(Integer value) {
        setDuration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value4(Integer value) {
        setGross(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value5(String value) {
        setGenres(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value6(String value) {
        setMovieTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value7(String value) {
        setPlotKeywords(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value8(String value) {
        setMovieImdbLink(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value9(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value10(String value) {
        setContentRating(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value11(Long value) {
        setBudget(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value12(Integer value) {
        setTitleYear(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value13(Double value) {
        setImdbScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value14(Long value) {
        setMovieFacebookLikes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord values(Long value1, String value2, Integer value3, Integer value4, String value5, String value6, String value7, String value8, String value9, String value10, Long value11, Integer value12, Double value13, Long value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MovieRecord
     */
    public MovieRecord() {
        super(Movie.MOVIE);
    }

    /**
     * Create a detached, initialised MovieRecord
     */
    public MovieRecord(Long movieId, String directorName, Integer duration, Integer gross, String genres, String movieTitle, String plotKeywords, String movieImdbLink, String country, String contentRating, Long budget, Integer titleYear, Double imdbScore, Long movieFacebookLikes) {
        super(Movie.MOVIE);

        set(0, movieId);
        set(1, directorName);
        set(2, duration);
        set(3, gross);
        set(4, genres);
        set(5, movieTitle);
        set(6, plotKeywords);
        set(7, movieImdbLink);
        set(8, country);
        set(9, contentRating);
        set(10, budget);
        set(11, titleYear);
        set(12, imdbScore);
        set(13, movieFacebookLikes);
    }
}
